"""Add S2 integration tables

Revision ID: a4abdba27633
Revises: b1fc42c056dc
Create Date: 2026-01-30 16:53:21.627550

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a4abdba27633"
down_revision: Union[str, None] = "b1fc42c056dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "s2_papers",
        sa.Column("s2_id", sa.String(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("venue", sa.Text(), nullable=True),
        sa.Column("authors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("tldr", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=False),
        sa.Column("reference_count", sa.Integer(), nullable=False),
        sa.Column("influential_citation_count", sa.Integer(), nullable=False),
        sa.Column("is_open_access", sa.Boolean(), nullable=False),
        sa.Column(
            "open_access_pdf", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "fields_of_study", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "publication_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("embedding", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("s2_id"),
    )
    op.create_table(
        "s2_citations",
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("contexts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("intents", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_influential", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["target_id"], ["s2_papers.s2_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("source_id", "target_id"),
    )
    op.alter_column(
        "collections",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.add_column("entries", sa.Column("s2_id", sa.String(), nullable=True))
    op.alter_column(
        "entries",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "entries",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.create_index(op.f("ix_entries_read"), "entries", ["read"], unique=False)
    op.create_index(op.f("ix_entries_s2_id"), "entries", ["s2_id"], unique=False)
    op.create_index(
        "ix_entries_type_year", "entries", ["entry_type", "year"], unique=False
    )
    op.create_index(
        "ix_entries_year_created", "entries", ["year", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_entries_year_created", table_name="entries")
    op.drop_index("ix_entries_type_year", table_name="entries")
    op.drop_index(op.f("ix_entries_s2_id"), table_name="entries")
    op.drop_index(op.f("ix_entries_read"), table_name="entries")
    op.alter_column(
        "entries",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "entries",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("entries", "s2_id")
    op.alter_column(
        "collections",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("collections", "description")
    op.drop_table("s2_citations")
    op.drop_table("s2_papers")
    # ### end Alembic commands ###
