"""Initial tables

Revision ID: b1fc42c056dc
Revises:
Create Date: 2026-01-29 21:59:34.925505

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b1fc42c056dc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("normalized", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_authors_normalized"), "authors", ["normalized"], unique=False
    )
    op.create_table(
        "collections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("citation_key", sa.String(length=255), nullable=False),
        sa.Column(
            "entry_type",
            sa.Enum(
                "ARTICLE",
                "BOOK",
                "BOOKLET",
                "INBOOK",
                "INCOLLECTION",
                "INPROCEEDINGS",
                "MANUAL",
                "MASTERSTHESIS",
                "MISC",
                "PHDTHESIS",
                "PROCEEDINGS",
                "TECHREPORT",
                "UNPUBLISHED",
                name="entry_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column(
            "required_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "optional_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("source_file", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entries_citation_key"), "entries", ["citation_key"], unique=True
    )
    op.create_index(op.f("ix_entries_year"), "entries", ["year"], unique=False)
    op.create_table(
        "collection_entries",
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["entry_id"], ["entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("collection_id", "entry_id"),
    )
    op.create_table(
        "entry_authors",
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["authors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["entry_id"], ["entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("entry_id", "author_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entry_authors")
    op.drop_table("collection_entries")
    op.drop_index(op.f("ix_entries_year"), table_name="entries")
    op.drop_index(op.f("ix_entries_citation_key"), table_name="entries")
    op.drop_table("entries")
    op.drop_table("collections")
    op.drop_index(op.f("ix_authors_normalized"), table_name="authors")
    op.drop_table("authors")
    # ### end Alembic commands ###
